apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: argo-learning-spoke
nodes:
- role: control-plane
  extraPortMappings:
  # Example Application
  - containerPort: 80
    hostPort: 8888
    protocol: TCP