apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jonmosco/argo-learning-env
    targetRevision: HEAD
    path: argo-cd/example-app/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
